#!/bin/bash
# =============================================================================
# PipeWire Audio Setup Script
# - Detect/install dependencies, then drive the Go interactive setup CLI
#   (audio/setup → soundbar-setup) which renders all configs from templates
#   straight to their final locations.
# - This script orchestrates: cleanup, package install, binary download, running
#   the wizard, the privileged udev install, service reload, and the firewall.
# - Bluetooth primary: a login catch-up unit starts the keepalive when the
#   soundbar was already connected before login, and (optional) a root oneshot
#   reconnects every paired Bluetooth device at boot.
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

WIREPLUMBER_CONF_DIR="$HOME/.config/wireplumber/wireplumber.conf.d"
PIPEWIRE_CONF_DIR="$HOME/.config/pipewire/pipewire.conf.d"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"
SCRIPTS_DIR="$HOME/.local/bin"
UDEV_DIR="/etc/udev/rules.d"

# --- Release source ---------------------------------------------------------
# Binaries are built by GitHub Actions and downloaded from the Release here, so
# this script needs no Go toolchain and works piped from curl. Override REPO or
# pin RELEASE_TAG via the environment if you fork or want a specific version.
REPO="${REPO:-JiPaix/reinstall}"
RELEASE_TAG="${RELEASE_TAG:-latest}"

# Temp workspace for the downloaded binaries + staged config. Auto-removed.
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

GENERATED_DIR="$WORK/generated"
SERVER_PORT=7921   # must match Environment=PORT= in soundbar-status-server.service

# fetch <asset> <dest> — download one asset from the GitHub Release.
fetch() {
  local asset="$1" dest="$2" url
  if [ "$RELEASE_TAG" = latest ]; then
    url="https://github.com/$REPO/releases/latest/download/$asset"
  else
    url="https://github.com/$REPO/releases/download/$RELEASE_TAG/$asset"
  fi
  curl -fSL --proto '=https' --tlsv1.2 "$url" -o "$dest"
}

print_header() { echo -e "\n${BOLD}${BLUE}=== $1 ===${NC}\n"; }
print_ok()     { echo -e "${GREEN}✓${NC} $1"; }
print_info()   { echo -e "${CYAN}→${NC} $1"; }
print_warn()   { echo -e "${YELLOW}!${NC} $1"; }
print_error()  { echo -e "${RED}✗${NC} $1"; }
ask()          { echo -e "${BOLD}$1${NC}"; }

# render_keepalive_login_unit <bt-input-name> <dest>
# The udev rule (99-soundbar-keepalive.rules) starts keepalive/loopback when the
# soundbar's input device appears. If that happened before the user manager
# existed (connected at boot, before login), the rule's `systemctl --user` call
# had no session to reach and nothing started. This oneshot catches that case
# at every login; when the soundbar isn't connected the condition skips it.
render_keepalive_login_unit() {
  local name="${1//%/%%}"   # systemd specifier escaping
  cat > "$2" <<EOF
[Unit]
Description=Start the soundbar keepalive at login if the soundbar is already connected
# Catch-up for 99-soundbar-keepalive.rules, which only fires on connect: when
# the soundbar connected before this user manager existed, nothing started.
# Generated by audio.sh.
After=pipewire-pulse.service
Wants=pipewire-pulse.service

[Service]
Type=oneshot
Environment="BT_INPUT_NAME=$name"
ExecCondition=/bin/sh -c 'grep -qxF -- "\$\$BT_INPUT_NAME" /sys/class/input/input*/name'
# --no-block: queue the starts rather than wait on them from inside a unit.
ExecStart=/usr/bin/systemctl --user --no-block start soundbar-keepalive.service soundbar-loopback.service

[Install]
WantedBy=default.target
EOF
}

# =============================================================================
# Prerequisite — PipeWire
# =============================================================================
# This configures an existing PipeWire setup; it does not install PipeWire.
# Packaging varies by distribution (pre-installed, split packages, …), so that
# is left to you. Check up front since even the cleanup below drives pactl.
for cmd in pipewire pactl wireplumber; do
  if ! command -v "$cmd" &>/dev/null; then
    print_error "$cmd not found — the PipeWire stack must be installed and running."
    print_info  "Install pipewire, pipewire-pulse and wireplumber for your distro, then retry."
    exit 1
  fi
done

# =============================================================================
# STEP 0 — Cleanup previous install if any
# =============================================================================
print_header "Cleaning Up Previous Config"

systemctl --user stop soundbar-keepalive.service 2>/dev/null && print_ok "Stopped soundbar-keepalive" || true
systemctl --user stop soundbar-loopback.service 2>/dev/null && print_ok "Stopped soundbar-loopback" || true
systemctl --user stop soundbar-status-server.service 2>/dev/null && print_ok "Stopped soundbar-status-server" || true

# keepalive/loopback are started and stopped by the udev rule (plus the login
# catch-up unit), never enabled: an enabled copy runs at every login even with
# the soundbar off, playing the tone on the fallback sink and pointing the
# default sink at bt_swap_sink. Undo an enable left behind by hand.
for unit in soundbar-keepalive.service soundbar-loopback.service; do
  systemctl --user is-enabled -q "$unit" 2>/dev/null \
    && systemctl --user disable "$unit" 2>/dev/null \
    && print_ok "Disabled $unit autostart (the udev rule drives it)" || true
done
if [ -f "$SYSTEMD_USER_DIR/soundbar-keepalive-login.service" ]; then
  systemctl --user disable soundbar-keepalive-login.service 2>/dev/null || true
  rm -f "$SYSTEMD_USER_DIR/soundbar-keepalive-login.service"
  print_ok "Removed previous soundbar-keepalive-login unit"
fi

# Unload any leftover pactl modules (only numeric IDs)
while IFS=$'\t' read -r mod_id mod_name _; do
  if [[ "$mod_id" =~ ^[0-9]+$ ]] && [[ "$mod_name" =~ remap|ladspa|swap|null-sink|loopback ]]; then
    pactl unload-module "$mod_id" 2>/dev/null && print_ok "Unloaded module $mod_name ($mod_id)" || true
  fi
done < <(pactl list short modules 2>/dev/null)

# Remove previous configs so virtual devices are gone before detection
[ -f "$PIPEWIRE_CONF_DIR/soundbar-eq.conf" ] && rm -f "$PIPEWIRE_CONF_DIR/soundbar-eq.conf" && print_ok "Removed previous EQ config"
[ -f "$WIREPLUMBER_CONF_DIR/99-device-priorities.conf" ] && rm -f "$WIREPLUMBER_CONF_DIR/99-device-priorities.conf" && print_ok "Removed previous WirePlumber config"
if [ -f "$UDEV_DIR/99-soundbar-keepalive.rules" ]; then
  sudo rm -f "$UDEV_DIR/99-soundbar-keepalive.rules"
  sudo udevadm control --reload-rules
  print_ok "Removed previous udev rule"
fi

# Remove the firewall rule (re-added in STEP 9) so it never stacks/goes stale.
if command -v ufw &>/dev/null; then
  sudo ufw delete allow "$SERVER_PORT/tcp" 2>/dev/null && print_ok "Removed ufw rule $SERVER_PORT/tcp" || true
fi

rm -rf "$GENERATED_DIR"
rm -f /tmp/soundbar-loopback-modules
rm -f "$HOME/.local/state/wireplumber/default-nodes"

# Restart PipeWire so bt_swap_sink virtual device disappears before we list devices
print_info "Restarting PipeWire to clear virtual devices..."
systemctl --user kill pipewire-pulse wireplumber pipewire 2>/dev/null || true
sleep 2
systemctl --user start pipewire
systemctl --user start wireplumber
systemctl --user start pipewire-pulse
sleep 4
print_ok "Cleanup done"

# =============================================================================
# STEP 1 — Package manager
# =============================================================================
print_header "Package Manager"
ask "Which package manager do you use?"
echo "  1) pacman"
echo "  2) paru"
echo "  3) yay"
read -rp "Choice [1-3]: " pm_choice

case $pm_choice in
  1) PKG_MANAGER="sudo pacman -S --noconfirm" ;;
  2) PKG_MANAGER="paru -S --noconfirm" ;;
  3) PKG_MANAGER="yay -S --noconfirm" ;;
  *) print_error "Invalid choice"; exit 1 ;;
esac

print_ok "Using: $PKG_MANAGER"

# =============================================================================
# STEP 2 — Verify the audio helpers (you install these; we only check)
# =============================================================================
# Like the PipeWire stack, the EQ/processing helpers are your responsibility —
# packaging varies by distro. We just confirm they're present and stop with a
# clear message if not.
print_header "Verifying Audio Helpers"

missing=()
command -v ffmpeg &>/dev/null || missing+=("ffmpeg")
# mbeq_1197.so comes from swh-plugins and needs the ladspa runtime. find exits 0
# even with no match, so test that it actually printed a path.
[ -n "$(find /usr/lib/ladspa -name 'mbeq_1197.so' 2>/dev/null)" ] || missing+=("ladspa + swh-plugins")

if [ ${#missing[@]} -gt 0 ]; then
  print_error "Missing audio helpers: ${missing[*]}"
  print_info  "Install ladspa, swh-plugins and ffmpeg for your distro, then retry."
  exit 1
fi
print_ok "Audio helpers present (ffmpeg, mbeq plugin)"

# =============================================================================
# STEP 3 — Download prebuilt binaries from the GitHub Release
# =============================================================================
print_header "Downloading Binaries"

if ! command -v curl &>/dev/null; then
  print_warn "curl not installed — installing with: $PKG_MANAGER"
  $PKG_MANAGER curl
fi

print_info "Fetching from $REPO ($RELEASE_TAG)"
fetch soundbar-setup                   "$WORK/soundbar-setup"
fetch soundbar-status-server           "$WORK/soundbar-status-server"
fetch soundbar-status-server.service   "$WORK/soundbar-status-server.service"
chmod +x "$WORK/soundbar-setup" "$WORK/soundbar-status-server"
print_ok "Downloaded soundbar-setup, soundbar-status-server, and unit file"

# =============================================================================
# STEP 5 — Interactive setup (renders all configs from templates)
# =============================================================================
print_header "Interactive Audio Setup"

print_info "Make sure all your devices are connected/paired before continuing."
print_warn "This needs pipewire-pulse running (it is) and an interactive terminal."

( cd "$WORK" && ./soundbar-setup -staging "$GENERATED_DIR" )

if [ ! -f "$GENERATED_DIR/vars.sh" ]; then
  print_error "setup did not produce $GENERATED_DIR/vars.sh — aborting"
  exit 1
fi
# shellcheck source=/dev/null
source "$GENERATED_DIR/vars.sh"
print_ok "Configs generated for: $PRIMARY_DESC"

# Ensure ~/.local/bin is in PATH (the generated scripts live there)
if [[ ":$PATH:" != *":$SCRIPTS_DIR:"* ]]; then
  print_warn "$SCRIPTS_DIR is not in your PATH"
  print_info "Add to your shell rc: export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# =============================================================================
# STEP 6 — Install the udev rule (Bluetooth only; needs root)
# =============================================================================
if [ "${IS_BT:-false}" = true ] && [ -n "${UDEV_RULE_FILE:-}" ] && [ -f "$UDEV_RULE_FILE" ]; then
  print_header "Installing udev Rule"
  sudo cp "$UDEV_RULE_FILE" "$UDEV_DIR/99-soundbar-keepalive.rules"
  sudo udevadm control --reload-rules
  print_ok "udev rule installed to $UDEV_DIR/99-soundbar-keepalive.rules"

  # Login catch-up: same input name the rule matches on, read back from it.
  BT_INPUT_NAME="$(sed -n 's/.*ATTRS{name}=="\([^"]*\)".*/\1/p' "$UDEV_RULE_FILE" | head -n1)"
  if [ -z "$BT_INPUT_NAME" ] || [[ "$BT_INPUT_NAME" == *[\"\\]* ]]; then
    print_warn "Could not read a usable input name from the udev rule — skipping the login catch-up unit"
  else
    mkdir -p "$SYSTEMD_USER_DIR"
    render_keepalive_login_unit "$BT_INPUT_NAME" "$SYSTEMD_USER_DIR/soundbar-keepalive-login.service"
    systemctl --user daemon-reload
    if systemctl --user enable soundbar-keepalive-login.service 2>/dev/null; then
      print_ok "Enabled soundbar-keepalive-login (keepalive at login when the soundbar is already connected)"
    else
      print_warn "Could not enable soundbar-keepalive-login"
    fi
  fi
else
  print_warn "Skipping udev rule (not a Bluetooth primary)"
fi

# =============================================================================
# STEP 6b — Bluetooth auto-connect at boot (optional; needs root)
# =============================================================================
# A Bluetooth soundbar usually won't reconnect on its own, so after a reboot the
# EQ/keepalive stay idle until someone connects it. This installs a root oneshot
# that retries connecting every device BlueZ already has paired, at every boot.
# It keeps no device list: pair something new and it is picked up next boot.
# System unit, not --user: it must run before anyone logs in; once the soundbar
# is connected, the udev rule / login catch-up unit take over.
BT_HELPER=/usr/local/bin/bt-autoconnect
BT_SERVICE=/etc/systemd/system/bt-autoconnect.service
bt_auto=n

if command -v bluetoothctl &>/dev/null; then
  print_header "Bluetooth Auto-Connect"
  ask "Reconnect paired Bluetooth devices automatically at boot? [y/N]"
  [ "${IS_BT:-false}" = true ] && print_info "Recommended: your primary device is Bluetooth."
  read -rp "Choice: " bt_auto
fi

case "${bt_auto,,}" in
  y|yes)
    sudo tee "$BT_HELPER" >/dev/null <<'BTEOF'
#!/bin/bash
# bt-autoconnect — try to connect every device BlueZ already knows about,
# retrying for a bounded window so devices that power on slowly still get
# picked up. Keeps no device list of its own: the set comes from BlueZ's paired
# registry, so pairing something new is enough for it to be picked up next boot.
# Installed by audio.sh; run at boot by bt-autoconnect.service. Optional
# tunables come from /etc/bt-autoconnect/bt-autoconnect.env.

set -u

ATTEMPTS="${BT_AUTOCONNECT_ATTEMPTS:-12}"
INTERVAL="${BT_AUTOCONNECT_INTERVAL:-10}"
SKIP="${BT_AUTOCONNECT_SKIP:-}"   # space-separated MACs to leave alone

skipped() {
  local mac=$1 s
  for s in $SKIP; do [ "${s^^}" = "${mac^^}" ] && return 0; done
  return 1
}

# bluetoothd may still be enumerating the adapter when we start.
for _ in $(seq 1 30); do
  bluetoothctl show >/dev/null 2>&1 && break
  sleep 1
done

bluetoothctl power on >/dev/null 2>&1

for attempt in $(seq 1 "$ATTEMPTS"); do
  mapfile -t paired < <(bluetoothctl devices Paired 2>/dev/null | awk '{print $2}')

  if [ "${#paired[@]}" -eq 0 ]; then
    echo "no paired devices known to BlueZ; nothing to do"
    exit 0
  fi

  pending=0
  for mac in "${paired[@]}"; do
    skipped "$mac" && continue

    info=$(bluetoothctl info "$mac" 2>/dev/null)
    case $info in *"Connected: yes"*) continue ;; esac

    pending=1
    name=$(printf '%s\n' "$info" | sed -n 's/^[[:space:]]*Name: //p' | head -1)
    if bluetoothctl connect "$mac" >/dev/null 2>&1; then
      echo "connected ${name:-unknown} ($mac)"
    else
      echo "attempt $attempt/$ATTEMPTS: ${name:-unknown} ($mac) not reachable"
    fi
  done

  if [ "$pending" -eq 0 ]; then
    echo "all known devices connected"
    exit 0
  fi

  [ "$attempt" -lt "$ATTEMPTS" ] && sleep "$INTERVAL"
done

echo "giving up after $ATTEMPTS attempts; some devices stayed unreachable"
exit 0
BTEOF
    sudo chmod 0755 "$BT_HELPER"
    print_ok "Installed $BT_HELPER"

    sudo tee "$BT_SERVICE" >/dev/null <<'BTSVC'
[Unit]
Description=Connect all BlueZ-known Bluetooth devices at boot
# System unit, not a --user one: bluetoothd is system-wide and the soundbar
# should come up whether or not a session has started yet (same reasoning as
# poweroff-server). The helper also waits for the adapter to be enumerated.
# Installed by audio.sh.
After=bluetooth.service
Wants=bluetooth.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/bt-autoconnect
Environment=PATH=/usr/local/bin:/usr/bin:/bin
# Optional tuning: BT_AUTOCONNECT_ATTEMPTS / _INTERVAL / _SKIP. Leading "-" so
# the unit still starts when the file was never created.
EnvironmentFile=-/etc/bt-autoconnect/bt-autoconnect.env
# The retry window is bounded (12 x 10s by default); cap it anyway so a wedged
# connect can never hold the boot transaction open.
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
BTSVC
    sudo systemctl daemon-reload
    sudo systemctl enable bt-autoconnect.service
    # --no-block: the first pass can retry for ~2 minutes; don't hold the install.
    sudo systemctl start --no-block bt-autoconnect.service
    print_ok "Enabled bt-autoconnect.service (connecting paired devices now and at every boot)"
    print_info "Optional tuning in /etc/bt-autoconnect/bt-autoconnect.env: BT_AUTOCONNECT_ATTEMPTS, BT_AUTOCONNECT_INTERVAL, BT_AUTOCONNECT_SKIP (MACs)"
    ;;
  *)
    if [ -f "$BT_SERVICE" ] || [ -f "$BT_HELPER" ]; then
      sudo systemctl disable --now bt-autoconnect.service 2>/dev/null || true
      sudo rm -f "$BT_SERVICE" "$BT_HELPER"
      sudo systemctl daemon-reload
      print_ok "Removed bt-autoconnect service + helper"
    fi
    ;;
esac

# =============================================================================
# STEP 7 — Reload PipeWire and apply disabled-card profiles
# =============================================================================
print_header "Reloading Services"

systemctl --user daemon-reload
systemctl --user kill pipewire-pulse wireplumber pipewire 2>/dev/null || true
sleep 2
systemctl --user start pipewire
systemctl --user start wireplumber
systemctl --user start pipewire-pulse
sleep 2

for card in "${DISABLED_CARDS[@]}"; do
  pactl set-card-profile "$card" off 2>/dev/null && print_ok "Disabled: $card" || print_warn "Could not disable: $card"
done
print_ok "PipeWire reloaded"

# Soundbar already connected during this install: its udev event is long past,
# so start keepalive/loopback now exactly like a login would.
if systemctl --user is-enabled -q soundbar-keepalive-login.service 2>/dev/null; then
  systemctl --user start soundbar-keepalive-login.service 2>/dev/null || true
  print_ok "Ran soundbar-keepalive-login (starts keepalive if the soundbar is connected)"
fi

# =============================================================================
# STEP 7b — HTTP server access control (optional)
# =============================================================================
# Neither check is required: an empty ALLOWED_IPS means no IP restriction, and
# the token is always generated but only enforced because the server checks it
# unconditionally once present in server.env. Written before the (re)start
# below so the fresh binary picks it up immediately via EnvironmentFile=.
print_header "HTTP Server Access Control"

SERVER_CONFIG_DIR="$HOME/.config/soundbar-status-server"
mkdir -p "$SERVER_CONFIG_DIR"
chmod 700 "$SERVER_CONFIG_DIR"

ask "Restrict soundbar-status-server access by IP?"
print_info "Comma-separated IPs and/or CIDRs, mixed freely (e.g. 192.168.1.3,10.0.0.0/24)."
read -rp "Allowed IPs (blank = no restriction): " ALLOWED_IPS

AUTH_TOKEN="$(head -c 32 /dev/urandom | base64)"

{
  echo "ALLOWED_IPS=$ALLOWED_IPS"
  echo "AUTH_TOKEN=$AUTH_TOKEN"
} > "$SERVER_CONFIG_DIR/server.env"
chmod 600 "$SERVER_CONFIG_DIR/server.env"

if [ -n "$ALLOWED_IPS" ]; then
  print_ok "Restricting access to: $ALLOWED_IPS"
else
  print_warn "No IP restriction set — reachable from any host that can route to it"
fi
print_ok "Generated auth token (send it as 'Authorization: Bearer <token>')"

# =============================================================================
# STEP 8 — Install and (re)start the status HTTP server
# =============================================================================
print_header "Soundbar Status HTTP Server"

cp "$WORK/soundbar-status-server" "$SCRIPTS_DIR/soundbar-status-server"
chmod +x "$SCRIPTS_DIR/soundbar-status-server"
print_ok "Installed $SCRIPTS_DIR/soundbar-status-server"

cp "$WORK/soundbar-status-server.service" "$SYSTEMD_USER_DIR/soundbar-status-server.service"
print_ok "Installed $SYSTEMD_USER_DIR/soundbar-status-server.service"

systemctl --user daemon-reload
systemctl --user enable soundbar-status-server.service 2>/dev/null && print_ok "Enabled soundbar-status-server" || true
systemctl --user restart soundbar-status-server.service
print_ok "(Re)started soundbar-status-server (HTTP :$SERVER_PORT)"

# =============================================================================
# STEP 9 — Firewall (open the status server port)
# =============================================================================
print_header "Firewall"

if command -v ufw &>/dev/null; then
  sudo ufw allow "$SERVER_PORT/tcp" comment 'soundbar-status-server'
  print_ok "Allowed $SERVER_PORT/tcp in ufw"
else
  print_warn "ufw not installed — skipping firewall rule for $SERVER_PORT/tcp"
fi

# =============================================================================
# Done
# =============================================================================
print_header "Setup Complete"
echo -e "${GREEN}${BOLD}All done!${NC}"
echo ""
echo -e "  Primary device: ${CYAN}${PRIMARY_DESC}${NC} (${PRIMARY_SINK})"
echo -e "  Status server:  ${CYAN}http://localhost:$SERVER_PORT/status${NC}"
echo -e "  Access token:   ${CYAN}$AUTH_TOKEN${NC}"
echo -e "  Token file:     ${CYAN}$SERVER_CONFIG_DIR/server.env${NC}"
if [ "${IS_BT:-false}" = true ]; then
  echo ""
  echo -e "${YELLOW}Connect your primary BT device to activate the EQ and keepalive.${NC}"
fi
