package main

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

//go:embed swapscreen.tmpl.sh
var engineTemplate string

const profilesMarker = "#__PROFILES__"

// formatScale renders a scale with minimal digits: 1.0→"1", 2.0→"2", 1.25→"1.25".
func formatScale(s float64) string { return strconv.FormatFloat(s, 'f', -1, 64) }

// cellSpec renders one monitor as a `key=value …` token string for the bash array.
func cellSpec(p Placed) string {
	parts := []string{
		"connector=" + p.Connector,
		"mode=" + p.ModeSpec,
		"vrr=" + strconv.FormatBool(p.VRR),
		"scale=" + formatScale(p.Scale),
		"color=" + p.Color,
		"x=" + strconv.Itoa(p.X),
		"y=" + strconv.Itoa(p.Y),
	}
	if p.Primary {
		parts = append(parts, "primary=true")
	}
	return strings.Join(parts, " ")
}

// arrayLiteral renders a bash array of monitor specs.
func arrayLiteral(name string, placed []Placed) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s=(\n", name)
	for _, p := range placed {
		fmt.Fprintf(&b, "    %q\n", cellSpec(p))
	}
	b.WriteString(")\n")
	return b.String()
}

// buildProfilesBlock renders the three profile arrays. taikoExtra holds the rows
// stacked on top of the monitor grid; the full taiko layout (monitor rows +
// extra) is auto-aligned and normalized as one grid, so its cells are emitted
// explicitly (it can't reuse MONITOR_PROFILE — the monitor rows shift down to
// make room above).
func buildProfilesBlock(monitor, tv Profile, taikoExtra [][]Cell) string {
	taiko := Profile{Rows: append(append([][]Cell{}, monitor.Rows...), taikoExtra...)}

	var b strings.Builder
	b.WriteString(arrayLiteral("MONITOR_PROFILE", monitor.AutoAlign()))
	b.WriteString(arrayLiteral("TV_PROFILE", tv.AutoAlign()))
	b.WriteString(arrayLiteral("TAIKO_PROFILE", taiko.AutoAlign()))
	return b.String()
}

// Generate writes profiles.conf (the captured arrays) and the rendered
// swapscreen.sh (the engine template with the arrays injected).
func Generate(profilesPath, scriptPath string, monitor, tv Profile, taikoExtra [][]Cell) error {
	block := strings.TrimRight(buildProfilesBlock(monitor, tv, taikoExtra), "\n")

	header := "# Généré par swapscreen-setup — ne pas éditer à la main.\n" +
		"# Reconfigurer : relancer ./screen.sh\n\n"
	if err := writeFile(profilesPath, header+block+"\n"); err != nil {
		return err
	}

	if !strings.Contains(engineTemplate, profilesMarker) {
		return fmt.Errorf("template is missing the %q marker", profilesMarker)
	}
	script := strings.Replace(engineTemplate, profilesMarker, block, 1)
	script = injectGeneratedHeader(script)
	return writeFile(scriptPath, script)
}

// injectGeneratedHeader inserts a "do not edit" banner just after the shebang.
func injectGeneratedHeader(script string) string {
	banner := "# GENERATED by swapscreen-setup from setup/swapscreen.tmpl.sh — do not edit.\n" +
		"# Reconfigure by re-running ./screen.sh"
	if nl := strings.IndexByte(script, '\n'); nl >= 0 {
		return script[:nl+1] + banner + "\n" + script[nl+1:]
	}
	return banner + "\n" + script
}

func writeFile(path, content string) error {
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
