package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenerateReproducesLegacyConfig rebuilds the hand-tuned monitor/tv/taiko
// layout and checks the generated profiles + script. taiko is normalized to
// non-negative space (Mutter rejects negative positions): DP-3 centered over
// DP-1 at the top (320, 0), the monitor row pushed down to y=1080.
func TestGenerateReproducesLegacyConfig(t *testing.T) {
	monitor := Profile{Rows: [][]Cell{{
		{Connector: "DP-1", W: 2560, H: 1440, ModeSpec: "2560x1440@164.958", Scale: 1, Color: "bt2100", VRR: true, Primary: true},
		{Connector: "DP-2", W: 1920, H: 1080, ModeSpec: "1920x1080@60.000", Scale: 1, Color: "default"},
	}}}
	tv := Profile{Rows: [][]Cell{{
		{Connector: "HDMI-1", W: 3840, H: 2160, ModeSpec: "3840x2160@60.000", Scale: 2, Color: "bt2100", Primary: true},
	}}}
	taikoExtra := [][]Cell{{
		{Connector: "DP-3", W: 1920, H: 1080, ModeSpec: "1920x1080@143.981", Scale: 1, Color: "bt2100", VRR: true},
	}}

	dir := t.TempDir()
	profilesPath := filepath.Join(dir, "profiles.conf")
	scriptPath := filepath.Join(dir, "swapscreen.sh")
	if err := Generate(profilesPath, scriptPath, monitor, tv, taikoExtra); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	profiles := readFile(t, profilesPath)
	wantLines := []string{
		// MONITOR_PROFILE: standalone grid, origin at (0,0).
		`"connector=DP-1 mode=2560x1440@164.958 vrr=true scale=1 color=bt2100 x=0 y=0 primary=true"`,
		`"connector=DP-2 mode=1920x1080@60.000 vrr=false scale=1 color=default x=2560 y=0"`,
		// TV_PROFILE.
		`"connector=HDMI-1 mode=3840x2160@60.000 vrr=false scale=2 color=bt2100 x=0 y=0 primary=true"`,
		// TAIKO_PROFILE: full grid normalized — DP-3 on top (320,0), monitors at y=1080.
		`"connector=DP-1 mode=2560x1440@164.958 vrr=true scale=1 color=bt2100 x=0 y=1080 primary=true"`,
		`"connector=DP-2 mode=1920x1080@60.000 vrr=false scale=1 color=default x=2560 y=1080"`,
		`"connector=DP-3 mode=1920x1080@143.981 vrr=true scale=1 color=bt2100 x=320 y=0"`,
	}
	for _, w := range wantLines {
		if !strings.Contains(profiles, w) {
			t.Errorf("profiles.conf missing line:\n  %s\n--- got ---\n%s", w, profiles)
		}
	}
	if strings.Contains(profiles, "${MONITOR_PROFILE[@]}") {
		t.Error("TAIKO_PROFILE should emit cells explicitly, not reuse MONITOR_PROFILE")
	}

	script := readFile(t, scriptPath)
	if strings.Contains(script, profilesMarker) {
		t.Errorf("generated script still contains the %q marker", profilesMarker)
	}
	if !strings.Contains(script, "GENERATED by swapscreen-setup") {
		t.Error("generated script missing the GENERATED header")
	}
	if !strings.Contains(script, "TAIKO_PROFILE=(") || !strings.Contains(script, "MONITOR_PROFILE=(") {
		t.Error("generated script missing injected profile arrays")
	}
}

// TestTaikoNormalizedNonNegative ensures the full taiko grid has no negative
// coordinates (Mutter rejects them), with the extra monitor centered on top.
func TestTaikoNormalizedNonNegative(t *testing.T) {
	monitor := Profile{Rows: [][]Cell{{
		{Connector: "DP-1", W: 2560, H: 1440, Scale: 1, Primary: true},
		{Connector: "DP-2", W: 1920, H: 1080, Scale: 1},
	}}}
	taiko := Profile{Rows: append(append([][]Cell{}, monitor.Rows...), []Cell{
		{Connector: "DP-3", W: 1920, H: 1080, Scale: 1},
	})}

	pos := map[string]Placed{}
	for _, p := range taiko.AutoAlign() {
		if p.X < 0 || p.Y < 0 {
			t.Errorf("%s at negative position (%d, %d)", p.Connector, p.X, p.Y)
		}
		pos[p.Connector] = p
	}
	if pos["DP-3"].X != 320 || pos["DP-3"].Y != 0 {
		t.Errorf("DP-3 at (%d,%d), want (320,0)", pos["DP-3"].X, pos["DP-3"].Y)
	}
	if pos["DP-1"].Y != 1080 {
		t.Errorf("DP-1 at y=%d, want 1080 (pushed below the taiko top row)", pos["DP-1"].Y)
	}
	if pos["DP-3"].Y >= pos["DP-1"].Y {
		t.Error("DP-3 should sit above DP-1")
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}
