package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestGenerateReproducesLegacyConfig rebuilds the hand-tuned monitor/tv/taiko
// layout and checks the generated profiles + script. taiko is normalized to
// non-negative space (Mutter rejects negative positions): DP-3 centered over
// DP-1 at the top (320, 0), the monitor row pushed down to y=1080.
func TestGenerateReproducesLegacyConfig(t *testing.T) {
	monitor := Profile{Rows: [][]Cell{{
		{Connector: "DP-1", W: 2560, H: 1440, ModeSpec: "2560x1440@164.958", Scale: 1, Color: "bt2100", VRR: true, Primary: true},
		{Connector: "DP-2", W: 1920, H: 1080, ModeSpec: "1920x1080@60.000", Scale: 1, Color: "default"},
	}}}
	tv := Profile{Rows: [][]Cell{{
		{Connector: "HDMI-1", W: 3840, H: 2160, ModeSpec: "3840x2160@60.000", Scale: 2, Color: "bt2100", Primary: true},
	}}}
	taikoExtra := [][]Cell{{
		{Connector: "DP-3", W: 1920, H: 1080, ModeSpec: "1920x1080@143.981", Scale: 1, Color: "bt2100", VRR: true},
	}}
	conns := []Connector{
		{Name: "DP-1", Vendor: "GSM", Product: "LG ULTRAGEAR", Serial: "0x001"},
		{Name: "DP-2", Vendor: "IVM", Product: "PL2788H", Serial: "0"},
		{Name: "DP-3", Vendor: "GSM", Product: "LG ULTRAGEAR", Serial: "0x002"},
		{Name: "HDMI-1", Vendor: "VES", Product: "65UHD_LCD_TV", Serial: "0"},
	}

	dir := t.TempDir()
	profilesPath := filepath.Join(dir, "profiles.conf")
	scriptPath := filepath.Join(dir, "swapscreen.sh")
	gdmPath := filepath.Join(dir, "gdm-monitors.xml")
	if err := Generate(profilesPath, scriptPath, gdmPath, "gnome", conns, monitor, tv, taikoExtra); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	profiles := readFile(t, profilesPath)
	if !strings.Contains(profiles, "BACKEND=gnome") {
		t.Errorf("profiles.conf missing BACKEND=gnome:\n%s", profiles)
	}
	wantLines := []string{
		// MONITOR_PROFILE: standalone grid, origin at (0,0).
		`"connector=DP-1 mode=2560x1440@164.958 vrr=true scale=1 color=bt2100 x=0 y=0 primary=true"`,
		`"connector=DP-2 mode=1920x1080@60.000 vrr=false scale=1 color=default x=2560 y=0"`,
		// TV_PROFILE.
		`"connector=HDMI-1 mode=3840x2160@60.000 vrr=false scale=2 color=bt2100 x=0 y=0 primary=true"`,
		// TAIKO_PROFILE: full grid normalized — DP-3 on top (320,0), monitors at y=1080.
		`"connector=DP-1 mode=2560x1440@164.958 vrr=true scale=1 color=bt2100 x=0 y=1080 primary=true"`,
		`"connector=DP-2 mode=1920x1080@60.000 vrr=false scale=1 color=default x=2560 y=1080"`,
		`"connector=DP-3 mode=1920x1080@143.981 vrr=true scale=1 color=bt2100 x=320 y=0"`,
	}
	for _, w := range wantLines {
		if !strings.Contains(profiles, w) {
			t.Errorf("profiles.conf missing line:\n  %s\n--- got ---\n%s", w, profiles)
		}
	}
	if strings.Contains(profiles, "${MONITOR_PROFILE[@]}") {
		t.Error("TAIKO_PROFILE should emit cells explicitly, not reuse MONITOR_PROFILE")
	}

	script := readFile(t, scriptPath)
	if strings.Contains(script, profilesMarker) {
		t.Errorf("generated script still contains the %q marker", profilesMarker)
	}
	if !strings.Contains(script, "BACKEND=gnome") {
		t.Error("generated script missing injected BACKEND=gnome")
	}
	if !strings.Contains(script, "GENERATED by swapscreen-setup") {
		t.Error("generated script missing the GENERATED header")
	}
	if !strings.Contains(script, "TAIKO_PROFILE=(") || !strings.Contains(script, "MONITOR_PROFILE=(") {
		t.Error("generated script missing injected profile arrays")
	}

	gdmXML := readFile(t, gdmPath)
	if strings.Count(gdmXML, "<logicalmonitor>") != 1 {
		t.Errorf("gdm-monitors.xml should have exactly one enabled logicalmonitor (the primary only):\n%s", gdmXML)
	}
	if !strings.Contains(gdmXML, "<connector>DP-1</connector>") || !strings.Contains(gdmXML, "<vendor>GSM</vendor>") {
		t.Errorf("gdm-monitors.xml should enable DP-1 (the monitor profile's primary) with its EDID:\n%s", gdmXML)
	}
	for _, disabled := range []string{"DP-2", "DP-3", "HDMI-1"} {
		if !strings.Contains(gdmXML, "<connector>"+disabled+"</connector>") {
			t.Errorf("gdm-monitors.xml missing a <disabled> entry for %s:\n%s", disabled, gdmXML)
		}
	}
	if strings.Count(gdmXML, "<disabled>") != 3 {
		t.Errorf("gdm-monitors.xml should disable every non-primary connector (3), got:\n%s", gdmXML)
	}
}

// TestTaikoNormalizedNonNegative ensures the full taiko grid has no negative
// coordinates (Mutter rejects them), with the extra monitor centered on top.
func TestTaikoNormalizedNonNegative(t *testing.T) {
	monitor := Profile{Rows: [][]Cell{{
		{Connector: "DP-1", W: 2560, H: 1440, Scale: 1, Primary: true},
		{Connector: "DP-2", W: 1920, H: 1080, Scale: 1},
	}}}
	taiko := Profile{Rows: append(append([][]Cell{}, monitor.Rows...), []Cell{
		{Connector: "DP-3", W: 1920, H: 1080, Scale: 1},
	})}

	pos := map[string]Placed{}
	for _, p := range taiko.AutoAlign() {
		if p.X < 0 || p.Y < 0 {
			t.Errorf("%s at negative position (%d, %d)", p.Connector, p.X, p.Y)
		}
		pos[p.Connector] = p
	}
	if pos["DP-3"].X != 320 || pos["DP-3"].Y != 0 {
		t.Errorf("DP-3 at (%d,%d), want (320,0)", pos["DP-3"].X, pos["DP-3"].Y)
	}
	if pos["DP-1"].Y != 1080 {
		t.Errorf("DP-1 at y=%d, want 1080 (pushed below the taiko top row)", pos["DP-1"].Y)
	}
	if pos["DP-3"].Y >= pos["DP-1"].Y {
		t.Error("DP-3 should sit above DP-1")
	}
}

// TestGenerateKDESkipsGDM checks the KDE backend injects BACKEND=kde and does
// NOT emit a gdm-monitors.xml (SDDM has no mutter-style greeter layout).
func TestGenerateKDESkipsGDM(t *testing.T) {
	monitor := Profile{Rows: [][]Cell{{
		{Connector: "DP-1", W: 2560, H: 1440, ModeSpec: "2560x1440@165", Scale: 1, Color: "bt2100", VRR: true, Primary: true},
	}}}
	tv := Profile{Rows: [][]Cell{{
		{Connector: "HDMI-A-1", W: 3840, H: 2160, ModeSpec: "3840x2160@60", Scale: 2, Color: "bt2100", Primary: true},
	}}}
	conns := []Connector{{Name: "DP-1"}, {Name: "HDMI-A-1"}}

	dir := t.TempDir()
	profilesPath := filepath.Join(dir, "profiles.conf")
	scriptPath := filepath.Join(dir, "swapscreen.sh")
	gdmPath := filepath.Join(dir, "gdm-monitors.xml")
	if err := Generate(profilesPath, scriptPath, gdmPath, "kde", conns, monitor, tv, nil); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	profiles := readFile(t, profilesPath)
	if !strings.Contains(profiles, "BACKEND=kde") {
		t.Errorf("profiles.conf missing BACKEND=kde:\n%s", profiles)
	}
	// The engine feeds mode= straight to kscreen-doctor; connector uses full DRM names.
	if !strings.Contains(profiles, "connector=HDMI-A-1 mode=3840x2160@60") {
		t.Errorf("profiles.conf missing the KDE TV record:\n%s", profiles)
	}
	if !strings.Contains(readFile(t, scriptPath), "BACKEND=kde") {
		t.Error("generated script missing injected BACKEND=kde")
	}
	if _, err := os.Stat(gdmPath); !os.IsNotExist(err) {
		t.Errorf("KDE backend should not write gdm-monitors.xml, but Stat err = %v", err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(b)
}
